version: "3.8"

services:
  db:
    image: bitnami/postgresql
    container_name: halloween-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=halloween
  redis:
    image: redis
    container_name: redis-db
    command: redis-server --requirepass gui123456
    ports:
      - 6379:6379
